version: "3"

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: bank_image:latest
    container_name: isi_c
    ports:
      - "8004:8004"
    volumes:
      - ./app:/code
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: pg_bank_container
    restart: always
    env_file:
      - ./app/config.env
    ports:
      - "8005:8005"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*' -c port=8005

volumes:
  postgres_data:
